### ISSUE TITLE
There is not "target/scala-2.11/gitbucket-gist-plugin_2.11-1.3.jar" file after hit "./sbt.sh package"?

### ISSUE THREAD

**Issue by srain** [takezoe/gitbucket-gist-plugin#18]
My system is centOS. The detail as below screen shots:
![20150803_171848](https://cloud.githubusercontent.com/assets/4929763/9034692/4de090d0-3a04-11e5-8556-561611cc670b.jpg)

![20150803_172044](https://cloud.githubusercontent.com/assets/4929763/9034696/541e429e-3a04-11e5-93df-603b103db822.jpg)

![20150803_172120](https://cloud.githubusercontent.com/assets/4929763/9034697/5443ec24-3a04-11e5-9929-0ab8549e11b1.jpg)

Would you please help to check this? Thanks!

**Comment by takezoe** [comment]
I expect memory is not enough to compile. Could you show spec of your machine?

**Comment by srain** [comment]
Yes, you're right! I restarted my server, then the package command was success. My server only has 1024M memory =)
